import React, { useState, useRef } from 'react';
import { Accordion, AccordionContent, AccordionPanel, AccordionTitle } from 'flowbite-react';
import { useChecklistsApi } from '../../services/checklists';
import { Checklist } from '../../types/api';

export default function CheckListAccor() {
  const {
    uploadChecklistFile,
    importChecklists,
    exportChecklists,
    getChecklistTemplate,
    loading,
    error,
  } = useChecklistsApi();

  const [selectedFile, setSelectedFile] = useState<File | null>(null);
  const [uploadProgress, setUploadProgress] = useState(0);
  const [importedChecklists, setImportedChecklists] = useState<Checklist[]>([]);
  const [aiPrompt, setAiPrompt] = useState('');
  const [isGenerating, setIsGenerating] = useState(false);
  const fileInputRef = useRef<HTMLInputElement>(null);

  // PDF Smart Import handlers
  const handleFileSelect = (event: React.ChangeEvent<HTMLInputElement>) => {
    const file = event.target.files?.[0];
    if (file && file.type === 'application/pdf') {
      setSelectedFile(file);
      setUploadProgress(0);
    } else {
      alert('Please select a valid PDF file');
    }
  };

  const handleUpload = async () => {
    if (!selectedFile) return;

    try {
      setUploadProgress(0);
      const result = await uploadChecklistFile(selectedFile);
      console.log('✅ File uploaded successfully:', result);
      setUploadProgress(100);
      setSelectedFile(null);
      if (fileInputRef.current) {
        fileInputRef.current.value = '';
      }
    } catch (error) {
      console.error('❌ Upload failed:', error);
      alert('Upload failed. Please try again.');
    }
  };

  const handleImport = async () => {
    try {
      const result = await importChecklists();
      console.log('✅ Import successful:', result);
      setImportedChecklists((prev) => [...prev, result]);
    } catch (error) {
      console.error('❌ Import failed:', error);
      alert('Import failed. Please try again.');
    }
  };

  const handleExport = async () => {
    try {
      const blob = await exportChecklists();
      const url = window.URL.createObjectURL(blob);
      const a = document.createElement('a');
      a.href = url;
      a.download = 'checklists.xlsx';
      document.body.appendChild(a);
      a.click();
      window.URL.revokeObjectURL(url);
      document.body.removeChild(a);
    } catch (error) {
      console.error('❌ Export failed:', error);
      alert('Export failed. Please try again.');
    }
  };

  const handleDownloadTemplate = async () => {
    try {
      const blob = await getChecklistTemplate();
      const url = window.URL.createObjectURL(blob);
      const a = document.createElement('a');
      a.href = url;
      a.download = 'checklist_template.xlsx';
      document.body.appendChild(a);
      a.click();
      window.URL.revokeObjectURL(url);
      document.body.removeChild(a);
    } catch (error) {
      console.error('❌ Template download failed:', error);
      alert('Template download failed. Please try again.');
    }
  };

  // AI Checklist Generation handlers
  const handleAiGenerate = async () => {
    if (!aiPrompt.trim()) {
      alert('Please enter a description for the checklist');
      return;
    }

    try {
      setIsGenerating(true);
      // Note: This would need to be implemented in the API
      // For now, we'll simulate the AI generation
      console.log('🤖 AI generating checklist for:', aiPrompt);

      // Simulate AI generation delay
      await new Promise((resolve) => setTimeout(resolve, 2000));

      // Mock generated checklist
      const generatedChecklist: Checklist = {
        id: `ai-generated-${Date.now()}`,
        name: `AI Generated: ${aiPrompt.substring(0, 50)}...`,
        description: `AI generated checklist based on: ${aiPrompt}`,
        workOrderId: undefined,
        tasks: [
          {
            id: `task-1-${Date.now()}`,
            assetId: undefined,
            type: 1,
            value: 'Task 1: Generated by AI',
          },
          {
            id: `task-2-${Date.now()}`,
            assetId: undefined,
            type: 1,
            value: 'Task 2: Based on your prompt',
          },
          {
            id: `task-3-${Date.now()}`,
            assetId: undefined,
            type: 1,
            value: 'Task 3: Ready for customization',
          },
        ],
      };

      setImportedChecklists((prev) => [...prev, generatedChecklist]);
      setAiPrompt('');
    } catch (error) {
      console.error('❌ AI generation failed:', error);
      alert('AI generation failed. Please try again.');
    } finally {
      setIsGenerating(false);
    }
  };

  return (
    <div className="space-y-6">
      {/* Error Display */}
      {error && (
        <div className="bg-red-100 border border-red-400 text-red-700 px-4 py-3 rounded mb-4">
          Error: {error.message}
        </div>
      )}

      {/* Accordion 1: PDF Smart Import */}
      <Accordion>
        <AccordionPanel>
          <AccordionTitle>PDF Smart Import</AccordionTitle>
          <AccordionContent>
            <div className="space-y-4">
              <p className="text-gray-600">
                Upload a PDF file to automatically extract and create checklists from the content.
              </p>

              {/* File Upload Section */}
              <div className="border-2 border-dashed border-gray-300 rounded-lg p-6">
                <div className="text-center">
                  <svg
                    className="mx-auto h-12 w-12 text-gray-400"
                    stroke="currentColor"
                    fill="none"
                    viewBox="0 0 48 48"
                  >
                    <path
                      d="M28 8H12a4 4 0 00-4 4v20m32-12v8m0 0v8a4 4 0 01-4 4H12a4 4 0 01-4-4v-4m32-4l-3.172-3.172a4 4 0 00-5.656 0L28 28M8 32l9.172-9.172a4 4 0 015.656 0L28 28m0 0l4 4m4-24h8m-4-4v8m-12 4h.02"
                      strokeWidth="2"
                      strokeLinecap="round"
                      strokeLinejoin="round"
                    />
                  </svg>
                  <div className="mt-4">
                    <label htmlFor="file-upload" className="cursor-pointer">
                      <span className="mt-2 block text-sm font-medium text-gray-900">
                        {selectedFile ? selectedFile.name : 'Choose a PDF file to upload'}
                      </span>
                      <input
                        ref={fileInputRef}
                        id="file-upload"
                        name="file-upload"
                        type="file"
                        accept=".pdf"
                        className="sr-only"
                        onChange={handleFileSelect}
                      />
                    </label>
                    <p className="mt-1 text-xs text-gray-500">PDF files only</p>
                  </div>
                </div>
              </div>

              {/* Upload Progress */}
              {uploadProgress > 0 && uploadProgress < 100 && (
                <div className="w-full bg-gray-200 rounded-full h-2.5">
                  <div
                    className="bg-blue-600 h-2.5 rounded-full transition-all duration-300"
                    style={{ width: `${uploadProgress}%` }}
                  ></div>
                </div>
              )}

              {/* Action Buttons */}
              <div className="flex space-x-3">
                <button
                  onClick={handleUpload}
                  disabled={!selectedFile || loading}
                  className="px-4 py-2 bg-blue-600 text-white rounded-md hover:bg-blue-700 disabled:opacity-50 disabled:cursor-not-allowed"
                >
                  {loading ? 'Uploading...' : 'Upload PDF'}
                </button>

                <button
                  onClick={handleImport}
                  disabled={loading}
                  className="px-4 py-2 bg-green-600 text-white rounded-md hover:bg-green-700 disabled:opacity-50"
                >
                  {loading ? 'Importing...' : 'Import Checklists'}
                </button>
              </div>

              {/* Template and Export */}
              <div className="flex space-x-3 pt-4 border-t">
                <button
                  onClick={handleDownloadTemplate}
                  className="px-4 py-2 bg-gray-600 text-white rounded-md hover:bg-gray-700"
                >
                  Download Template
                </button>

                <button
                  onClick={handleExport}
                  disabled={loading}
                  className="px-4 py-2 bg-purple-600 text-white rounded-md hover:bg-purple-700 disabled:opacity-50"
                >
                  {loading ? 'Exporting...' : 'Export Checklists'}
                </button>
              </div>
            </div>
          </AccordionContent>
        </AccordionPanel>
      </Accordion>

      {/* Accordion 2: AI Checklist Generation */}
      <Accordion>
        <AccordionPanel>
          <AccordionTitle>AI Checklist Generation</AccordionTitle>
          <AccordionContent>
            <div className="space-y-4">
              <p className="text-gray-600">
                Describe what you need and let AI generate a comprehensive checklist for you.
              </p>

              {/* AI Prompt Input */}
              <div>
                <label htmlFor="ai-prompt" className="block text-sm font-medium text-gray-700 mb-2">
                  Describe your checklist requirements:
                </label>
                <textarea
                  id="ai-prompt"
                  rows={4}
                  value={aiPrompt}
                  onChange={(e) => setAiPrompt(e.target.value)}
                  className="w-full px-3 py-2 border border-gray-300 rounded-md focus:outline-none focus:ring-2 focus:ring-blue-500"
                  placeholder="e.g., Create a checklist for equipment maintenance including safety checks, cleaning procedures, and inspection points..."
                />
              </div>

              {/* Generate Button */}
              <button
                onClick={handleAiGenerate}
                disabled={!aiPrompt.trim() || isGenerating}
                className="px-6 py-3 bg-gradient-to-r from-purple-600 to-pink-600 text-white rounded-md hover:from-purple-700 hover:to-pink-700 disabled:opacity-50 disabled:cursor-not-allowed flex items-center space-x-2"
              >
                {isGenerating ? (
                  <>
                    <svg className="animate-spin h-4 w-4" fill="none" viewBox="0 0 24 24">
                      <circle
                        className="opacity-25"
                        cx="12"
                        cy="12"
                        r="10"
                        stroke="currentColor"
                        strokeWidth="4"
                      ></circle>
                      <path
                        className="opacity-75"
                        fill="currentColor"
                        d="M4 12a8 8 0 018-8V0C5.373 0 0 5.373 0 12h4zm2 5.291A7.962 7.962 0 014 12H0c0 3.042 1.135 5.824 3 7.938l3-2.647z"
                      ></path>
                    </svg>
                    <span>Generating...</span>
                  </>
                ) : (
                  <>
                    <svg className="h-4 w-4" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                      <path
                        strokeLinecap="round"
                        strokeLinejoin="round"
                        strokeWidth="2"
                        d="M13 10V3L4 14h7v7l9-11h-7z"
                      />
                    </svg>
                    <span>Generate with AI</span>
                  </>
                )}
              </button>
            </div>
          </AccordionContent>
        </AccordionPanel>
      </Accordion>

      {/* Generated Checklists Display */}
      {importedChecklists.length > 0 && (
        <div className="mt-6">
          <h3 className="text-lg font-semibold text-gray-900 mb-4">Generated Checklists</h3>
          <div className="space-y-3">
            {importedChecklists.map((checklist, index) => (
              <div
                key={checklist.id || index}
                className="bg-white border border-gray-200 rounded-lg p-4 shadow-sm"
              >
                <h4 className="font-medium text-gray-900">{checklist.name}</h4>
                <p className="text-sm text-gray-600 mt-1">{checklist.description}</p>
                {checklist.tasks && checklist.tasks.length > 0 && (
                  <ul className="mt-2 text-sm text-gray-500">
                    {checklist.tasks.slice(0, 3).map((task, taskIndex) => (
                      <li key={taskIndex} className="flex items-center">
                        <span className="w-1.5 h-1.5 bg-gray-400 rounded-full mr-2"></span>
                        {typeof task.value === 'string' ? task.value : `Task ${taskIndex + 1}`}
                      </li>
                    ))}
                    {checklist.tasks.length > 3 && (
                      <li className="text-gray-400">
                        ... and {checklist.tasks.length - 3} more tasks
                      </li>
                    )}
                  </ul>
                )}
              </div>
            ))}
          </div>
        </div>
      )}
    </div>
  );
}
